<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="ip-192-168-2-48.ec2.internal" name="tests.LoginTests" tests="3" failures="1" timestamp="31 Jan 2019 17:43:19 GMT" time="13.552" errors="0">
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="7.191" classname="tests.LoginTests"/>
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="3.100" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="3.261" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]">
      <![CDATA[java.lang.AssertionError: expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.LoginPage.verifyLoginPassword_aroundBody4(LoginPage.java:43)
at pages.LoginPage$AjcClosure5.run(LoginPage.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at pages.LoginPage.verifyLoginPassword(LoginPage.java:43)
at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
</testsuite> <!-- tests.LoginTests -->
